version: "3.9"

services:
  mongodb:
    image: mongo:7
    ports:
      - "0.0.0.0:27017:27017"
    volumes:
      - mongodb-data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "0.0.0.0:6379:6379"

  school-service:
    build:
      context: .
      dockerfile: services/school-service/Dockerfile
    env_file:
      - services/school-service/.env
    depends_on:
      - mongodb
      - redis
    ports:
      - "0.0.0.0:3007:3007"

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    env_file:
      - services/auth-service/.env
    depends_on:
      - mongodb
      - redis
      - school-service
    ports:
      - "0.0.0.0:3001:3001"

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    env_file:
      - services/user-service/.env
    depends_on:
      - mongodb
      - redis
    ports:
      - "0.0.0.0:3002:3002"

  academic-service:
    build:
      context: .
      dockerfile: services/academic-service/Dockerfile
    env_file:
      - services/academic-service/.env
    depends_on:
      - mongodb
      - redis
    ports:
      - "0.0.0.0:3003:3003"

  attendance-service:
    build:
      context: .
      dockerfile: services/attendance-service/Dockerfile
    env_file:
      - services/attendance-service/.env
    depends_on:
      - mongodb
      - redis
    ports:
      - "0.0.0.0:3004:3004"

  fee-service:
    build:
      context: .
      dockerfile: services/fee-service/Dockerfile
    env_file:
      - services/fee-service/.env
    depends_on:
      - mongodb
      - redis
    ports:
      - "0.0.0.0:3005:3005"

  notification-service:
    build:
      context: .
      dockerfile: services/notification-service/Dockerfile
    env_file:
      - services/notification-service/.env
    depends_on:
      - mongodb
      - redis
    ports:
      - "0.0.0.0:3006:3006"

  admin-service:
    build:
      context: .
      dockerfile: services/admin-service/Dockerfile
    env_file:
      - services/admin-service/.env
    depends_on:
      - mongodb
      - redis
    ports:
      - "0.0.0.0:3008:3007"

  api-gateway:
    build:
      context: .
      dockerfile: services/api-gateway/Dockerfile
    env_file:
      - services/api-gateway/.env
    depends_on:
      - auth-service
      - user-service
      - academic-service
      - attendance-service
      - fee-service
      - notification-service
      - school-service
      - admin-service
    ports:
      - "0.0.0.0:8000:8000"

volumes:
  mongodb-data:
